**Logical Operators**

AI ML Class Lesson 1

In [1]:
print("Welcome to the world of AI/ML")

Welcome to the world of AI/ML


In [2]:
print(5)

5


## Numberic Data types

In [3]:
x = 10
y = 10.56
z = 10 + 11j

In [4]:
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'float'>
<class 'complex'>


In [5]:
x = "Machine learning"

In [6]:
print(type(x))

<class 'str'>


In [9]:
is_stored = True

In [10]:
print(type(is_stored))

<class 'bool'>


In [11]:
print(5>3)

True


In [13]:
print(len("Mahipal"))

7


Variable - a name given to a memory location to store data

In [25]:
text = "Artificial"
print(text[6:9])

cia


In [29]:
word = "MachineLearning"

In [30]:
print(word[0:15:2])

Mcieerig


In [40]:
name = "Tommy"
salary = 50000

In [41]:
print(f"Hello {name} your salary is {salary}")

Hello Tommy your salary is 50000


In [42]:
text = "PyThon"

In [50]:
print(text.lower())

python


In [51]:
print(text.upper())
print(

PYTHON


In [4]:
password = input("Enter your password: ")
if password == "pa55w0rd":
    print("Login Successful")
else:
    print("Try again!")

Enter your password:  pa55w0rd


Login Successful


In [2]:
data = [
    (101, "Rahul", 80000, "India", "Fraud"),
    (102, "Amit", 30000, "India", "Safe"),
    (103, "John", 90000, "USA", "Fraud"),
    (101, "Rahul", 80000, "India", "Fraud"),
    (104, "Sara", 40000, "USA", "Safe"),
    (105, "Mike", 120000, "USA", "Fraud")
]

# 1. Remove duplicate records
# 2. Convert data into dictionary format
# 3. create a set of unique countries
# 4. identify high income customers (>80k)
# 5. count fraud customers
# 6. skip customers with income < 40k
# 7. stop processing if income > 1 lakh found
# 8. store final result as tuple

In [5]:
set(data)
dic(data)

NameError: name 'dic' is not defined

In [2]:
def func():
    print("Hello")
    func()
func()

Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hell

RecursionError: maximum recursion depth exceeded

In [ ]:
Do we have other do it now/
 
Logicmojo Education (29 Mar 2026, 5:15 PM)
data = [
    "User: Mahipal | Phone: 9876543210 | Email: mahi@gmail.com | Amount: Rs.5000",
    "User: Ravi | Phone: 98765abc10 | Email: ravi#gmail.com | Amount: USD300",
    "User: NULL | Phone: 9123456789 | Email: test@yahoo.com | Amount: Rs.7000",
    "User: Ankit | Phone: 9999999999 | Email: ankit@gmail.com | Amount: Rs.0",
    "User: Sita | Phone: 8888888888 | Email: sita@gmail.com | Amount: Rs.-100"
]


1.HANDLE EXCEPTIONS
Safely process each record
Skip bad records but log errors

2. USE ASSERT
Ensure:
User name is not NULL
Amount > 0

3. REGEX EXTRACTION
Extract:
name
phone (valid 10 digits only)
email (valid format)
amount (only numbers)

4. ADVANCED REGEX
Extract currency:
Rs
USD

5. STRING CLEANING
lowercase everything
remove special characters


6. FINAL OUTPUT
Return clean structured dataset:
[
 {'name': 'mahipal', 'phone': '9876543210', 'email': 'mahi@gmail.com', 'amount': 5000, 'currency': 'rs'},
 ...
]
 
Athulya VK (29 Mar 2026, 5:17 PM)
yes
 
Prashant Patel (29 Mar 2026, 5:17 PM)
yes
 
Deeksha Das (29 Mar 2026, 5:17 PM)
yes
 
Dhina (29 Mar 2026, 5:17 PM)
yes
 
You (29 Mar 2026, 5:17 PM)
Thank You!

In [1]:
import numpy as np

age = [25, 30, 35, 40]
salary = [40000, 50000, 60000, 70000]
experience = [2,5,7,10]

In [2]:
#1. convert all into numpy arrays
agen = np.array(age)
salaryn = np.array(salary)
experiencen = np.array(experience)
print(agen)
print(salaryn)
print(experiencen)

[25 30 35 40]
[40000 50000 60000 70000]
[ 2  5  7 10]


In [3]:
#2. convert all arrays into column format
col_age = agen.reshape(-1,1)
col_salary = salaryn.reshape(-1,1)
col_experience = experiencen.reshape(-1,1)
print(col_age)
print(col_salary)
print(col_experience)

[[25]
 [30]
 [35]
 [40]]
[[40000]
 [50000]
 [60000]
 [70000]]
[[ 2]
 [ 5]
 [ 7]
 [10]]


In [5]:
#3. combine all feature into a datset
dataset = np.hstack((col_age, col_salary, col_experience))
print(dataset)

[[   25 40000     2]
 [   30 50000     5]
 [   35 60000     7]
 [   40 70000    10]]


In [11]:
#4. increase all salaries by 10%
dataset = dataset.astype(float)
dataset[:, 1] = dataset[:, 1] * 1.1
print(dataset)

[[2.50e+01 4.84e+04 2.00e+00]
 [3.00e+01 6.05e+04 5.00e+00]
 [3.50e+01 7.26e+04 7.00e+00]
 [4.00e+01 8.47e+04 1.00e+01]]


In [16]:
#5. Normalize salary (divide my max salary)
max_sal = np.max(dataset[:, 1])
print(max_sal)
dataset[:, 1] = dataset[:, 1]/max_sal
print(dataset)

84700.0
[[25.          0.57142857  2.        ]
 [30.          0.71428571  5.        ]
 [35.          0.85714286  7.        ]
 [40.          1.         10.        ]]


In [19]:
#6. Extract all ages, first employee record
all_ages =  dataset[:,0]
print(all_ages)
first_emp = dataset[0,:]
print(first_emp)


[25. 30. 35. 40.]
[25.          0.57142857  2.        ]
