In [5]:
file = open("sample.txt", "w")
file.close()

In [6]:
with open("test.txt", "r") as file:
    data = file.read()
    print(data)

sjdbjksdbcjksdj
osddjvksdksdn
ksdjcksdnksdnkvnsd


In [10]:
with open("test.txt", "w") as file:
    file.write("Hello AI/ML")
    
with open("test.txt", "r") as file:    
    data = file.read()
    print(data)

Hello AI/ML


In [27]:
with open("test.txt", "w+") as file:
    file.write("hello team")
    file.seek(0)
    data = file.read()
    print(data)

hello team


In [ ]:
file = open("D:/Reports/products.txt", "w")
file.write(products.txt)
file.close()

In [29]:
with open("test.txt", "w") as file:
    file.write("Hello AI/ML")
    file.write("Welcome")
    
with open("test.txt", "r") as file:    
    data = file.read()
    print(data)

Hello AI/MLWelcome


In [30]:
lines = ["Hello people\n", "welcome to python\n", "fjwehfdjkwhcc\n", "what else\n", "Do your assignment\n"]
with open("test.txt", "w") as file:
    file.writelines(lines)

with open("test.txt", "r") as file:    
    print(file.read())

Hello people
welcome to python
fjwehfdjkwhcc
what else
Do your assignment



In [31]:
lines = ["Hello people\n", "welcome to python\n", "fjwehfdjkwhcc\n", "what else\n", "Do your assignment\n"]
with open("test.txt", "a") as file:
    file.writelines(lines)

with open("test.txt", "r") as file:    
    print(file.read())

Hello people
welcome to python
fjwehfdjkwhcc
what else
Do your assignment
Hello people
welcome to python
fjwehfdjkwhcc
what else
Do your assignment



In [33]:
lines = ["Hello people\n", "welcome to python\n", "fjwehfdjkwhcc\n", "what else\n", "Do your assignment\n"]
with open("test.txt", "r") as file:
    lines = file.readlines()

lines.insert(2, "Hope you got it\n")
with open("test.txt", "w") as file:
    file.writelines(lines)

with open("test.txt", "r") as file:    
    print(file.read())

Hello people
welcome to python
Hope you got it
Wlcomesjdbfhd
fjwehfdjkwhcc
what else
Do your assignment
Hello people
welcome to python
fjwehfdjkwhcc
what else
Do your assignment



In [34]:
with open("test.txt", "r") as file:
    line1 = file.readline()
    line2 = file.readline()
    
    print(line1)
    print(line2)

Hello people

welcome to python



In [36]:
with open("test.txt", "r") as file:
    lines = file.readlines()
    
    print(lines[5])

what else



In [38]:
with open("test.txt", "r") as file:
    for i, line in enumerate(file):
        if i == 4:
            print(line)
            break

fjwehfdjkwhcc



In [40]:
with open("data_cleaning_dataset.csv", "r") as file:
    for line in file:
        print(line)

CustomerID,Age,Gender,City,Monthly_Income,Purchase_Amount

1051,23.0,Female,Chennai,45510.0,7679.0

1092,32.0,Male,Delhi,39426.0,10826.0

1014,60.0,Female,Mumbai,,12287.0

1071,54.0,Male,Bangalore,37850.0,2060.0

1060,50.0,Female,Mumbai,86150.0,14112.0

1020,25.0,Female,Delhi,107312.0,18150.0

1082,61.0,Female,Bangalore,,5280.0

1086,61.0,Male,Mumbai,94910.0,18811.0

1074,22.0,Female,Chennai,72375.0,12394.0

1074,56.0,Female,Bangalore,,2856.0

1087,21.0,Male,Mumbai,116443.0,5290.0

1099,23.0,Female,Delhi,77132.0,17190.0

1023,62.0,Male,Delhi,98945.0,10681.0

1002,49.0,Female,Bangalore,102050.0,7557.0

1021,69.0,Male,Mumbai,115402.0,16582.0

1052,47.0,Male,Bangalore,22983.0,1161.0

1001,64.0,Female,Bangalore,117241.0,5144.0

1087,52.0,Male,Mumbai,,16211.0

1029,57.0,Male,Mumbai,43510.0,3420.0

1037,69.0,Male,Chennai,98187.0,16502.0

1001,33.0,Male,Mumbai,60998.0,14525.0

1063,30.0,Male,Delhi,76846.0,9446.0

1059,67.0,Male,Bangalore,,13232.0

1020,59.0,Female,Bangalore,26640.0,6736.0

10

In [41]:
with open("data_cleaning_dataset.csv", "r") as file:
    for line in file:
        line = line.strip() #remove\n
        columns = line.split(",")
        print(columns)

['CustomerID', 'Age', 'Gender', 'City', 'Monthly_Income', 'Purchase_Amount']
['1051', '23.0', 'Female', 'Chennai', '45510.0', '7679.0']
['1092', '32.0', 'Male', 'Delhi', '39426.0', '10826.0']
['1014', '60.0', 'Female', 'Mumbai', '', '12287.0']
['1071', '54.0', 'Male', 'Bangalore', '37850.0', '2060.0']
['1060', '50.0', 'Female', 'Mumbai', '86150.0', '14112.0']
['1020', '25.0', 'Female', 'Delhi', '107312.0', '18150.0']
['1082', '61.0', 'Female', 'Bangalore', '', '5280.0']
['1086', '61.0', 'Male', 'Mumbai', '94910.0', '18811.0']
['1074', '22.0', 'Female', 'Chennai', '72375.0', '12394.0']
['1074', '56.0', 'Female', 'Bangalore', '', '2856.0']
['1087', '21.0', 'Male', 'Mumbai', '116443.0', '5290.0']
['1099', '23.0', 'Female', 'Delhi', '77132.0', '17190.0']
['1023', '62.0', 'Male', 'Delhi', '98945.0', '10681.0']
['1002', '49.0', 'Female', 'Bangalore', '102050.0', '7557.0']
['1021', '69.0', 'Male', 'Mumbai', '115402.0', '16582.0']
['1052', '47.0', 'Male', 'Bangalore', '22983.0', '1161.0']
['10

In [51]:
import csv
with open("data_cleaning_dataset.csv", "r") as file:
    reader = csv.reader(file)
    next(reader)
    for row in reader:
        age = row[1]
        print(age)

23.0
32.0
60.0
54.0
50.0
25.0
61.0
61.0
22.0
56.0
21.0
23.0
62.0
49.0
69.0
47.0
64.0
52.0
57.0
69.0
33.0
30.0
67.0
59.0
47.0
36.0
34.0
36.0
45.0
43.0
54.0
43.0
40.0
26.0
29.0
18.0
18.0
64.0
51.0
49.0
65.0
42.0
57.0
62.0
18.0
33.0
56.0
22.0
39.0
46.0
20.0
29.0

33.0
68.0
54.0
39.0
46.0
31.0
45.0
22.0
64.0
66.0
47.0
63.0
69.0


33.0
43.0
43.0
65.0

56.0
53.0
50.0
47.0
54.0
40.0
27.0
22.0
53.0
51.0
69.0

27.0
36.0
49.0
18.0
22.0
62.0
21.0

41.0
33.0
19.0
66.0
45.0
49.0
44.0
37.0
41.0
29.0
67.0
52.0
50.0
50.0
68.0
60.0
54.0
29.0
20.0
18.0
50.0
57.0
27.0
60.0
61.0
46.0
30.0
29.0
48.0
63.0
19.0
68.0
67.0
52.0
40.0
34.0
43.0
25.0
46.0
43.0

43.0
51.0
68.0
58.0
24.0
21.0
67.0
62.0
28.0
46.0
53.0
42.0
38.0
53.0
27.0
54.0
26.0
41.0
52.0
66.0
52.0
65.0
53.0
35.0

56.0
49.0
41.0
40.0
49.0
54.0
29.0
66.0

40.0
42.0
52.0
58.0
47.0
34.0
66.0

65.0
42.0

30.0
36.0
66.0
53.0
29.0
58.0
36.0

26.0
24.0
45.0
31.0
48.0
69.0
36.0

33.0
22.0
52.0
29.0
42.0
69.0
38.0
53.0
40.0
33.0
56.0
62.0
59.0

31.0
48.0
2

In [58]:
class Bank:
    def __init__(self, balance):
        self.balance = balance

b1 = Bank(1000)
print(b1.balance)

1000


In [61]:
class Bank:
    def __init__(self, balance):
        self.balance = balance

    def deposit(self, amount):
        self.balance += amount
    


b1 = Bank(1000)
b1.deposit(2000)
print(b1.balance)

3000


In [64]:
class Bank:
    def __init__(self, balance):
        self.__balance = balance

    def deposit(self, amount):
        self.__balance += amount
    def get_balance(self):
        return self.__balance


b1 = Bank(1000)
b1.deposit(500)
print(b1.get_balance())

1500


In [65]:
class Person:
    def speak(self):
        print("I can speak")

class Employee(Person):
    pass

e1 = Employee()
e1.speak()

I can speak


In [69]:
class Dog:
    def sound(self):
        print("Bark")

class Cat:
    def sound(self):
        print("Meow")

d = Dog()
c = Cat()

d.sound()
c.sound()

print("Using polymorphism")
animals = [Dog(), Cat()]
for animal in animals:
    animal.sound()
        

Bark
Meow
Using polymorphism
Bark
Meow


In [70]:
class Dog:
    def sound(self):
        print("Bark")

class Cat:
    def sound(self):
        print("Meow")

def make_sound(animal):
    animal.sound()

make_sound(Dog())
make_sound(Cat())

Bark
Meow


In [74]:
class Bank:
    def __init__(self, balance):
        self.__balance = balance #private variable
    def deposit(self, amount):
        self.__balance += amount #access controlled here
    def get_balance(self):
        return self.__balance #controlled access

b1 = Bank(1000)

print(b1.get_balance())

1000


In [11]:
import numpy as np

array_1d = np.array([1,2,3])
print(array_1d)
print(array_1d[0])
print(array_1d.dtype)

[1 2 3]
1
int32


In [18]:
array_2d = np.array([[1,2,3], [4,5,6]])
print(array_2d)
print(array_2d[1][0])
print(type(array_2d))
print(array_2d.shape)

[[1 2 3]
 [4 5 6]]
4
<class 'numpy.ndarray'>
(2, 3)


In [20]:
array_3d = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])
print(array_3d)
print(array_3d[0][0][0])
print(array_3d[1][1][1])
print(array_3d.shape)
print(array_3d.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
8
(2, 2, 2)
3


In [21]:
import numpy as np

arr = np.array([10,20,30,40])

print(arr.shape)
print(arr.ndim)

(4,)
1


In [26]:
ar = np.arange(0,10) #Range generator
print(ar)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
arr_zeroes = np.zeros((2, 3))
print(arr_zeroes)

[[0. 0. 0.]
 [0. 0. 0.]]


In [28]:
arr_one = np.ones((2, 3))
print(arr_one)

[[1. 1. 1.]
 [1. 1. 1.]]


In [33]:
arr = (np.random.rand(3,3) * 100) - 50
print(arr)

[[ 19.90493132 -48.15853961   9.15337832]
 [-43.83086373  13.42497048 -17.71959728]
 [-14.150738   -34.59255001  36.3530471 ]]


In [35]:
I = np.eye(3, dtype=int)
print(I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [36]:
import numpy as np

arr = np.array([[1,2], [3,4]])

for row in arr:
    print(row)

for element in np.nditer(arr):
    print(element)

[1 2]
[3 4]
1
2
3
4


In [37]:
arr = np.array([10,20,30,40])
result = arr * 2
print(result)


[20 40 60 80]


In [38]:
arr = np.array([10,20,30,40])
result = arr + 5
print(result)


[15 25 35 45]


In [42]:
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(3,2)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [47]:
import numpy as np

a = np.array([1,2])
b = np.array([3,4])

#vertical stacking
v = np.vstack([a, b])

#horizontal stacking
h = np.hstack([a, b])
print(v)
print(h)

[[1 2]
 [3 4]]
[1 2 3 4]


In [48]:
arr = np.array([10,20,30,40])

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

25.0
25.0
11.180339887498949
125.0


In [54]:
import numpy as np
salary = np.array([20000, 30000, 40000])

# add bonus 10%
# reshape
# combine with experience

salary_update = salary * 1.10

salary_update = salary_update.reshape(-1,1)

experience = np.array([4,5,6]).reshape(-1,1)

dataset = np.hstack((salary_update, experience))
#dataset = dataset.astype(int)
np.set_printoptions(suppress=False)
print(dataset)

[[2.2e+04 4.0e+00]
 [3.3e+04 5.0e+00]
 [4.4e+04 6.0e+00]]


In [56]:
import numpy as np

ar_2 = np.array([[10,20,30], [40,50,60]])

print(ar_2)
#mean across row (axis=1)
row_mean = np.mean(ar_2, axis=1)

#mean across columns (axis=1)
col_mean = np.mean(ar_2, axis=0)

print("row mean: ", row_mean)
print("col_mean: ", col_mean)

[[10 20 30]
 [40 50 60]]
row mean:  [20. 50.]
col_mean:  [25. 35. 45.]


In [ ]:
age = [25, 30, 35, 40]
salary = [40000, 50000, 60000, 70000]
experience = [2,5,7,10]

#1. convert all into numpy arrays
#2. convert all arrays into column format
#3. cobine all feature into a datset
#4. increase all salaries by 10%
#5. Normalize salary (divide my max salary)
#6. Extract all ages, first employee record
#7. calculate mean salary, median experience and std dev of age
#8. iterate through dataset and print each row

In [58]:
class Employee:
    def __init__(self, salary):
        self._salary = salary

emp = Employee(50000)
print(emp._salary)

50000


In [61]:
import numpy as np

age = np.array([25, 30, 35, 40])
salary = np.array([40000, 50000, 60000, 70000])
experience = np.array([2, 5, 7, 10])


age = age.reshape(-1, 1)         
salary = salary.reshape(-1, 1)   
experience = experience.reshape(-1, 1)


dataset = np.hstack((age, salary, experience))  
print("Final Dataset:\n", dataset)


salary_updated = salary * 1.10   # vectorized
print("\nUpdated Salary:\n", salary_updated)


max_salary = np.max(salary_updated)
salary_normalized = salary_updated / max_salary  
# broadcasting: each value divided by max
print("\nNormalized Salary:\n", salary_normalized)


print("\nAll Ages:", dataset[:, 0])
print("\nFirst Employee:", dataset[0])


print("\nMean Salary:", np.mean(salary))
print("Median Experience:", np.median(experience))  
print("Std Age:", np.std(age))  


print("\nIterating through dataset:")
for row in dataset: 
    print(row)

Final Dataset:
 [[   25 40000     2]
 [   30 50000     5]
 [   35 60000     7]
 [   40 70000    10]]

Updated Salary:
 [[44000.]
 [55000.]
 [66000.]
 [77000.]]

Normalized Salary:
 [[0.57142857]
 [0.71428571]
 [0.85714286]
 [1.        ]]

All Ages: [25 30 35 40]

First Employee: [   25 40000     2]

Mean Salary: 55000.0
Median Experience: 6.0
Std Age: 5.5901699437494745

Iterating through dataset:
[   25 40000     2]
[   30 50000     5]
[   35 60000     7]
[   40 70000    10]
